package com.flutterwave.bean;

public enum ChargeTypes {

    CARD,
    BANK_TRANSFER,
    DEBIT_NG_ACCOUNT,
    DEBIT_UK_ACCOUNT,
    ACH_PAYMENT,
    APPLEPAY,
    GOOGLEPAY,
    FAWRY_PAY,
    PAYPAL,
    MPESA,
    MOBILE_MONEY_GHANA,
    MOBILE_MONEY_UGANDA,
    MOBILE_MONEY_FRANCO,
    MOBILE_MONEY_RWANDA,
    MOBILE_MONEY_ZAMBIA,
    USSD,
    ACCOUNT

}
